name: design_system_project
description: "A Flutter design system package that provides a comprehensive set of UI components, styles, and assets for building consistent and beautiful Flutter applications."
publish_to: 'none'  # Keep as none since we're using Git

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.2.2+5

environment:
  sdk: '>=3.6.2 <4.0.0'
  flutter: ">=3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  extended_image: ^10.0.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.1.0
  flutter_svg_provider: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_gen: ^5.10.0
  build_runner: ^2.4.15
  storybook_flutter: ^0.14.1

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  component_creator: ^0.0.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/empty_state/
    - assets/branding/
    - assets/vuesax/
    - assets/social/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: IconsaxPlusBold
      fonts:
        - asset: assets/fonts/Iconsax/IconsaxPlusBold.ttf
    - family: IconsaxPlusBroken
      fonts:
        - asset: assets/fonts/Iconsax/IconsaxPlusBroken.ttf
    - family: IconsaxPlusLinear
      fonts:
        - asset: assets/fonts/Iconsax/IconsaxPlusLinear.ttf
    - family: SF Pro Display # This is the name you'll use in your TextStyle
      fonts:
        - asset: assets/fonts/SF-Pro-Display/SF-Pro-Display-Black.otf
          weight: 900 # Corresponds to FontWeight.w900 (Black)
        - asset: assets/fonts/SF-Pro-Display/SF-Pro-Display-BlackItalic.otf
          weight: 900
          style: italic
        - asset: assets/fonts/SF-Pro-Display/SF-Pro-Display-Bold.otf
          weight: 700 # Corresponds to FontWeight.w700 (Bold)
        - asset: assets/fonts/SF-Pro-Display/SF-Pro-Display-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/SF-Pro-Display/SF-Pro-Display-Heavy.otf
          weight: 800 # Corresponds to FontWeight.w800 (ExtraBold/Heavy)
        - asset: assets/fonts/SF-Pro-Display/SF-Pro-Display-HeavyItalic.otf
          weight: 800
          style: italic
        - asset: assets/fonts/SF-Pro-Display/SF-Pro-Display-Light.otf
          weight: 300 # Corresponds to FontWeight.w300 (Light)
        - asset: assets/fonts/SF-Pro-Display/SF-Pro-Display-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/SF-Pro-Display/SF-Pro-Display-Medium.otf
          weight: 500 # Corresponds to FontWeight.w500 (Medium)
        - asset: assets/fonts/SF-Pro-Display/SF-Pro-Display-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/SF-Pro-Display/SF-Pro-Display-Regular.otf
          weight: 400 # Corresponds to FontWeight.w400 (Regular/Normal)
        - asset: assets/fonts/SF-Pro-Display/SF-Pro-Display-RegularItalic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/SF-Pro-Display/SF-Pro-Display-Semibold.otf
          weight: 600 # Corresponds to FontWeight.w600 (Semibold)
        - asset: assets/fonts/SF-Pro-Display/SF-Pro-Display-SemiboldItalic.otf
          weight: 600
          style: italic
        - asset: assets/fonts/SF-Pro-Display/SF-Pro-Display-Thin.otf
          weight: 100 # Corresponds to FontWeight.w100 (Thin)
        - asset: assets/fonts/SF-Pro-Display/SF-Pro-Display-ThinItalic.otf
          weight: 100
          style: italic
        - asset: assets/fonts/SF-Pro-Display/SF-Pro-Display-Ultralight.otf
          weight: 200 # Corresponds to FontWeight.w200 (ExtraLight/Ultralight)
        - asset: assets/fonts/SF-Pro-Display/SF-Pro-Display-UltralightItalic.otf
          weight: 200
          style: italic
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

# flutter_gen: A code generator for assets, fonts, colors and more. It generates code to help you access assets type-safely.
flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    image: false
    flutter_svg: false
    rive: false
    lottie: false
  
  assets:
    # Optional
    enabled: true
    # Optional
    outputs:
      # Optional
      # Set to true if you want this package to be a package dependency
      # See: https://flutter.dev/docs/development/ui/assets-and-images#from-packages
      package_parameter_enabled: true  # Changed to true for package publishing
      # Optional
      # Available values:
      # - camel-case
      # - snake-case
      # - dot-delimiter
      style: dot-delimiter
      class_name: DSAssets
    exclude:
      - "**/@2x/**"
      - "**/@3x/**"
      - "**/*@2x.*"
      - "**/*@3x.*"

  fonts:
    # Optional
    enabled: true
    # Optional
    outputs:
      class_name: Fonts
