// GENERATED CODE - DO NOT MODIFY BY HAND
// This file is automatically generated by the catalog generator script
// Run: dart run lib/scripts/generate_catalog.dart

import 'package:flutter/material.dart';

// Import all demo files
import '../components/ds_image_view/ds_image_view.demo.dart';
import '../components/ds_button/ds_button.demo.dart';
import '../components/ds_loading/ds_loading.demo.dart';

/// Widget demo data structure
class WidgetDemo {
  final String name;
  final Widget demoWidget;

  const WidgetDemo({
    required this.name,
    required this.demoWidget,
  });
}

/// List of all available widget demos
/// This list is automatically generated from .demo.dart files
final List<WidgetDemo> demos = [
  WidgetDemo(
    name: 'DsImageView',
    demoWidget: const ImageViewDemo(),
  ),
  WidgetDemo(
    name: 'DsButton',
    demoWidget: const DSButtonDemo(),
  ),
  WidgetDemo(
    name: 'DsLoading',
    demoWidget: const LoadingDemo(),
  ),
];

/// Helper function to get demo by name
WidgetDemo? getDemoByName(String name) {
  try {
    return demos.firstWhere((demo) => demo.name == name);
  } catch (e) {
    return null;
  }
}

/// Helper function to get all demo names
List<String> getAllDemoNames() {
  return demos.map((demo) => demo.name).toList();
}
