import 'dart:io';

import 'package:flutter/foundation.dart';

/// Script to automatically generate catalog from .demo.dart files
///
/// Usage: dart run lib/scripts/generate_catalog.dart
///
/// This script:
/// 1. Scans lib/components/ directory for .demo.dart files
/// 2. Extracts class names from demo files
/// 3. Generates widget_demos.g.dart with imports and demo list
void main() async {
  final componentsDir = Directory('lib/components');
  if (!await componentsDir.exists()) {
    exit(1);
  }

  final demoFiles = <String>[];
  final demoClasses = <String>[];
  final imports = <String>[];

  // Recursively scan for .demo.dart files
  await _scanForDemoFiles(componentsDir, demoFiles, demoClasses, imports);

  if (demoFiles.isEmpty) {
    return;
  }

  // for (final file in demoFiles) {}

  // Generate the catalog file
  await _generateCatalogFile(demoFiles, demoClasses, imports);
}

/// Recursively scan directory for .demo.dart files
Future<void> _scanForDemoFiles(
  Directory dir,
  List<String> demoFiles,
  List<String> demoClasses,
  List<String> imports,
) async {
  await for (final entity in dir.list()) {
    if (entity is File && entity.path.endsWith('.demo.dart')) {
      final relativePath = entity.path.replaceFirst('lib/', '');
      demoFiles.add(relativePath);

      // Extract class name from file
      final className = await _extractClassName(entity);
      if (className != null) {
        demoClasses.add(className);
        imports.add("import '../$relativePath';");
      }
    } else if (entity is Directory) {
      await _scanForDemoFiles(entity, demoFiles, demoClasses, imports);
    }
  }
}

/// Extract class name from demo file
Future<String?> _extractClassName(File file) async {
  try {
    final content = await file.readAsString();
    final lines = content.split('\n');

    for (final line in lines) {
      // Look for class definition pattern: class ClassName
      // extends StatelessWidget
      final classMatch =
          RegExp(r'class\s+(\w+)\s+extends\s+StatelessWidget').firstMatch(line);
      if (classMatch != null) {
        return classMatch.group(1);
      }
    }
  } catch (e) {
    if (kDebugMode) {
      print('Error reading file ${file.path}: $e');
    }
  }

  return null;
}

/// Generate the catalog file
Future<void> _generateCatalogFile(
  List<String> demoFiles,
  List<String> demoClasses,
  List<String> imports,
) async {
  final catalogContent = _buildCatalogContent(demoFiles, demoClasses, imports);

  final catalogFile = File('lib/catalog/widget_demos.g.dart');
  await catalogFile.writeAsString(catalogContent);
}

/// Build the catalog file content
String _buildCatalogContent(
  List<String> demoFiles,
  List<String> demoClasses,
  List<String> imports,
) {
  final buffer = StringBuffer()

    // Header
    ..writeln('// GENERATED CODE - DO NOT MODIFY BY HAND')
    ..writeln(
      '// This file is automatically generated by the catalog generator script',
    )
    ..writeln('// Run: dart run lib/scripts/generate_catalog.dart')
    ..writeln('')
    ..writeln("import 'package:flutter/material.dart';")
    ..writeln('')
    ..writeln('// Import all demo files');

  // Imports
  for (final import in imports) {
    buffer.writeln(import);
  }
  buffer
    ..writeln('')

    // Widget demo class
    ..writeln('/// Widget demo data structure')
    ..writeln('class WidgetDemo {')
    ..writeln('  final String name;')
    ..writeln('  final Widget demoWidget;')
    ..writeln('')
    ..writeln('  const WidgetDemo({')
    ..writeln('    required this.name,')
    ..writeln('    required this.demoWidget,')
    ..writeln('  });')
    ..writeln('')

    // Demos list
    ..writeln('/// List of all available widget demos')
    ..writeln('/// This list is automatically generated from .demo.dart files')
    ..writeln('final List<WidgetDemo> demos = [');

  for (int i = 0; i < demoClasses.length; i++) {
    final className = demoClasses[i];
    final fileName = demoFiles[i].split('/').last.replaceAll('.demo.dart', '');
    final displayName = _formatDisplayName(fileName);

    buffer
      ..writeln('  WidgetDemo(')
      ..writeln("    name: '$displayName',")
      ..writeln('    demoWidget: const $className(),')
      ..writeln('  ),');
  }

  buffer
    ..writeln('];')
    ..writeln('')

    // Helper functions
    ..writeln('/// Helper function to get demo by name')
    ..writeln('WidgetDemo? getDemoByName(String name) {')
    ..writeln('  try {')
    ..writeln('    return demos.firstWhere((demo) => demo.name == name);')
    ..writeln('  } catch (e) {')
    ..writeln('    return null;')
    ..writeln('  }')
    ..writeln('')
    ..writeln('/// Helper function to get all demo names')
    ..writeln('List<String> getAllDemoNames() {')
    ..writeln('  return demos.map((demo) => demo.name).toList();')
    ..writeln('}');

  return buffer.toString();
}

/// Format display name from file name
String _formatDisplayName(String fileName) {
  // Convert snake_case to PascalCase
  final parts = fileName.split('_');
  final formattedParts = parts.map((part) {
    if (part.isEmpty) {
      return '';
    }
    return part[0].toUpperCase() + part.substring(1);
  });

  return formattedParts.join('');
}
